<?php


namespace app\controllers;


use yii\web\Controller;

abstract class BaseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    /**
     * 是否登陆了
     */
    public function isLogin() {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect('/user/sign-in');
        }
    }

}